version: '2'
services:
  dbpostgres:
    image: postgres:9.5
    restart: always
    environment:
          POSTGRES_USER: west223
          POSTGRES_PASSWORD: westwest223
          POSTGRES_DB: telegram_db
    ports:
        - "5434:5432"

    volumes:
      - ./postgres:/var/lib/postgresql

  admin:
    build: adminyii
    restart: always
    ports:
      - "8889:80"
    depends_on:
       - dbpostgres
    volumes:
      - ./adminyii:/app

  bot:
    build : ./docker-work
    restart: always
    command: python ./telegrambot/main.py
    depends_on:
          - dbpostgres
    volumes:
      - ./docker-work:/data

